### PR TITLE
 Issue #SB-7869 feat: Design for front end review comments

### PR DESCRIPTION
**Pull request by ttplsudhir**

### CODE REVIEW

**Comment by ttplsudhir** [comment]
@lakhanmandloi - Please review PR

**Comment by ttplsudhir** [comment]
@lakhanmandloi - Please review PR

**Comment by lakhanmandloi** [comment]
@ttplsudhir pls resolve this conflict asap.

**Comment by ttplsudhir** [comment]
@lakhanmandloi Resolved

**Pull request merged**
