### PR TITLE
SB-7808 - UI fixes for content credit popup

### PR DESCRIPTION
**Pull request by lakhanmandloi**

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
@harishgilimi , Hi can you pls merge this?

**Comment by harishgilimi** [comment]
@lakhanmandloi  update labels and titles with resource bundles for multilingual , Raghavendra already added resource bundles you can refer them

**Comment by lakhanmandloi** [comment]
@harishgilimi - Hi, I have updated text with resources bundle. Can you pls review it now? Thanks!

**Comment by harishgilimi** [comment]
@lakhanmandloi  travis build is failing please check

**Comment by lakhanmandloi** [comment]
@harishgilimi Hi, All checks are passing now.

**Pull request merged**
